networks:
  dev:

services:
  gateway:
    build:
      target: gateway
    networks:
      - dev
    ports:
      - 8080:8080

  worker:
    build: 
      target: worker
    networks:
      - dev
    ports:
      - 8000:8000